@startuml Manage Car (Get One)

header Rental Car Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Car (Get One)"

actor "User" as user
actor "Admin" as admin
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:cars" as routerCars
participant "<<controllers>>\n:cars" as controllersCars
participant "<<model>>\n:cars" as modelCars
database "<<MongoDB>>\n:cars" as CarsDatabase

user -> server ++: req.get('/Cars/:id')
admin -> server ++: req.get('/Cars/:id')

server -> routerCars ++: app.use('/Cars', Cars)
routerCars -> controllersCars ++: getCar()
controllersCars -> modelCars ++: findById(req.params.id)
modelCars ->  CarsDatabase ++: CarSchema
modelCars <-- CarsDatabase --: car
controllersCars <-- modelCars --: car
user <- controllersCars --: response
admin <- controllersCars --: response

@enduml
